/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UADpJZBYRO7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function About() {
  return (
    (<section
      className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center text-center space-y-6">
          <div className="space-y-4">
            <h1
              className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
              About Our Company
            </h1>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              At Acme Inc., we are dedicated to providing innovative solutions that empower our clients to achieve their
              goals. With a team of passionate experts, we strive to deliver exceptional service and drive meaningful
              impact.
            </p>
          </div>
          <form className="w-full max-w-md space-y-2">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <Input className="w-full" placeholder="Enter your name" type="text" />
              <Input className="w-full" placeholder="Enter your email" type="email" />
            </div>
            <Button className="w-full" type="submit">
              Join Our Newsletter
            </Button>
          </form>
        </div>
      </div>
    </section>)
  );
}
