/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MXtbd17yMDo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Hero() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1
              className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
              Unlock the Power of Web Development
            </h1>
            <p
              className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Streamline your web development process with our cutting-edge tools and resources. Build stunning,
              responsive websites with ease.
            </p>
          </div>
          <div className="w-full max-w-sm space-y-2">
            <form className="flex space-x-2">
              <Input className="max-w-lg flex-1" placeholder="Enter your email" type="email" />
              <Button className="bg-[#6366F1] hover:bg-[#4F46E5] text-white" type="submit">
                Get Started
              </Button>
            </form>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Sign up to unlock exclusive features and stay ahead of the curve.
              <Link className="underline underline-offset-2" href="#">
                Terms & Conditions
              </Link>
            </p>
          </div>
        </div>
      </div>
    </section>)
  );
}
