/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MXtbd17yMDo
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function Hero() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
              Unlock the Power of Web Development
            </h1>
            <p className="mx-auto max-w-[900px] text-gray-500 md:text-xl dark:text-gray-400">
              Jelajahi dunia baru streaming online dengan web kami yang
              memanfaatkan Named Data Networking (NDN). Rasakan keunggulan
              teknologi terdepan dalam pengalaman streaming yang lebih cepat,
              handal, dan aman. Temukan era baru hiburan digital dengan web
              streaming berbasis NDN: Terhubung, Cepat, Tanpa Batas!
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
